// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Del(arg1) {
  return window['go']['etcd']['EtcdClient']['Del'](arg1);
}

export function DelByKeyword(arg1) {
  return window['go']['etcd']['EtcdClient']['DelByKeyword'](arg1);
}

export function DelByPrefix(arg1) {
  return window['go']['etcd']['EtcdClient']['DelByPrefix'](arg1);
}

export function Get(arg1) {
  return window['go']['etcd']['EtcdClient']['Get'](arg1);
}

export function Get2String(arg1) {
  return window['go']['etcd']['EtcdClient']['Get2String'](arg1);
}

export function ListKeyByKeyword(arg1) {
  return window['go']['etcd']['EtcdClient']['ListKeyByKeyword'](arg1);
}

export function ListKeyByPrefix(arg1) {
  return window['go']['etcd']['EtcdClient']['ListKeyByPrefix'](arg1);
}

export function ListKeyValueByPrefix(arg1) {
  return window['go']['etcd']['EtcdClient']['ListKeyValueByPrefix'](arg1);
}

export function ListValueByKeyword(arg1) {
  return window['go']['etcd']['EtcdClient']['ListValueByKeyword'](arg1);
}

export function ListValueByPrefix(arg1) {
  return window['go']['etcd']['EtcdClient']['ListValueByPrefix'](arg1);
}

export function Put(arg1, arg2) {
  return window['go']['etcd']['EtcdClient']['Put'](arg1, arg2);
}

export function PutCompact(arg1, arg2) {
  return window['go']['etcd']['EtcdClient']['PutCompact'](arg1, arg2);
}
