// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['etcd']['EtcdClient']['Get'](arg1);
}

export function Get2String(arg1) {
  return window['go']['etcd']['EtcdClient']['Get2String'](arg1);
}

export function Put(arg1, arg2) {
  return window['go']['etcd']['EtcdClient']['Put'](arg1, arg2);
}

export function PutCompact(arg1, arg2) {
  return window['go']['etcd']['EtcdClient']['PutCompact'](arg1, arg2);
}
