// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Get(arg1:string):Promise<models.KeyVal>;

export function Get2String(arg1:string):Promise<string>;

export function Put(arg1:string,arg2:string):Promise<void>;

export function PutCompact(arg1:string,arg2:string):Promise<void>;
